name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
    - name: Lint with flake8
      run: |
        conda install flake8
        pip install flake8-html
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --format=html --htmldir ./reports/flake8 --statistics --tee --output-file ./reports/flake8/flake8stats.txt
    - name: Install HyVR-fork
      run: |
        pip install .
    - name: Install genbadge
      run: |
        pip install genbadge[all]
    - name: Test with pytest
      run: |
        conda install pytest
        pip install pytest-html
        pytest --junitxml=reports/junit/junit.xml --html=reports/junit/report.html
    - name: Coverage tests
      run: |
        pip install coverage
        NUMBA_DISABLE_JIT=1 coverage run -m pytest
        coverage report -m
        coverage xml -o reports/coverage/coverage.xml
        coverage html -d reports/coverage/html
    - name: Generate badges
      run: |
        genbadge coverage
        genbadge flake8
        genbadge pytest
