# This workflow is based on the example at https://github.com/conda-incubator/setup-miniconda
# It will install Python dependencies from the environment.yml file and run tests on multiple Python versions.

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up mamba
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: strict
          activate-environment: hyvr-dev
          environment-file: environment.yml
          use-mamba: true

      - name: Install package
        shell: bash -l {0}
        run: |
          pip install . --no-deps

      - name: Test with pytest
        shell: bash -l {0}
        run: |
          pip install pytest
          NUMBA_DISABLE_JIT=1 pytest
